#!/bin/sh
# Assault Wing Management Server
if [ $# -ne 3 ]; then
  echo Usage: run-aw-management-server SERVER_PORT LOG_DIR SCREEN_NAME
  exit 1
fi
SERVER_ROOT=/home/ville/AW2MasterServer
SERVER_PORT=$1
LOG_DIR=$2
SCREEN_NAME=$3
cd $SERVER_ROOT
if [ ! -d $LOG_DIR ]; then mkdir $LOG_DIR; fi
cd $LOG_DIR
screen -DR $SCREEN_NAME java -Xmx32m -classpath $SERVER_ROOT/bin aw2.master.ServerMain $SERVER_PORT
